/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Challenge1: typeof import('./components/Challenge-1.vue')['default']
    Challenge2: typeof import('./components/Challenge-2.vue')['default']
    Challenge3: typeof import('./components/Challenge-3.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Heaver: typeof import('./components/Heaver.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
